title: CSE15l Lab Reports
author: "Kevin Shen"

theme: minima

base_url: /cse15l-lab-reports

# Minima social links
github_username: abstrqt

# Minima: custom header links
header_pages:
  - reports/report1.md
  
include:
    - reports

exclude: 
    - .gitignore
    - LICENSE
    - README.md
